local_backend:
  # when using a custom proxy server port
  url: http://localhost:8082/api/v1
backend:
  name: git-gateway
  branch: master

media_folder: "static/uploads"
public_folder: "/uploads"

i18n:
  structure: multiple_folders
  locales: [de, en]
  default_locale: de

collections:
  - name: "homepages"
    label: "Homepages"
    folder: "homepages"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Intro", name: "intro", widget: "string" }
      - label: "Intro Section"
        name: "intro_section"
        widget: "object"
        collapsed: true
        fields:
          - { label: "Headline", name: "headline", widget: "string" }
          - { label: "Intro Content", name: "intro_content", widget: "text" }
          - { label: "Intro Quote", name: "intro_quote", widget: "string" }
          - { label: "Outro Content", name: "outro_content", widget: "text" }
          - { label: "Outro Quote", name: "outro_quote", widget: "string" }
          - {
              label: "Competitor List",
              name: "competitor_list",
              widget: "list",
              label_singular: "fact",
              field: { label: Fact, name: fact, widget: string },
            }
          - {
              label: "Vanevo List",
              name: "vanevo_list",
              widget: "list",
              label_singular: "fact",
              field: { label: Fact, name: fact, widget: string },
            }
      - label: "How Section"
        name: "how_section"
        widget: "object"
        collapsed: true
        fields:
          - { label: "Headline", name: "headline", widget: "string" }
          - {
              label: "Intro Content",
              name: "intro_content",
              widget: "markdown",
            }
          - { label: "Quote", name: "quote", widget: "string" }
          - label: "Image"
            name: "image"
            widget: "object"
            collapsed: true
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Alt", name: "alt", widget: "string" }
          - {
              label: "Outro Content",
              name: "outro_content",
              widget: "markdown",
            }
      - label: "Where Section"
        name: "where_section"
        widget: "object"
        collapsed: true
        fields:
          - { label: "Headline", name: "headline", widget: "string" }
          - label: "Image"
            name: "image"
            widget: "object"
            collapsed: true
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Alt", name: "alt", widget: "string" }
          - {
              label: "Intro Content",
              name: "intro_content",
              widget: "markdown",
            }
          - { label: "Quote", name: "quote", widget: "string" }
          - {
              label: "Outro Content",
              name: "outro_content",
              widget: "markdown",
            }
          - {
              label: "Where List",
              name: "where_list",
              widget: "list",
              label_singular: "fact",
              field: { label: Fact, name: fact, widget: string },
            }
      - label: "Team Section"
        name: "team_section"
        widget: "object"
        collapsed: true
        fields:
          - { label: "Headline", name: "headline", widget: "string" }
          - label: "Image"
            name: "image"
            widget: "object"
            collapsed: true
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Alt", name: "alt", widget: "string" }
          - { label: "Content", name: "content", widget: "markdown" }
          - { label: "Quote", name: "quote", widget: "string" }
          - label: "Team"
            name: "team"
            widget: "object"
            collapsed: true
            fields:
              - label: "Jan"
                name: "jan"
                widget: "object"
                collapsed: true
                fields:
                  - label: "Image"
                    name: "image"
                    widget: "object"
                    collapsed: true
                    fields:
                      - { label: "Image", name: "image", widget: "image" }
                      - { label: "Alt", name: "alt", widget: "string" }
                  - { label: "Name", name: "name", widget: "string" }
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "About", name: "about", widget: "text" }
              - label: "Arne"
                name: "arne"
                widget: "object"
                collapsed: true
                fields:
                  - label: "Image"
                    name: "image"
                    widget: "object"
                    collapsed: true
                    fields:
                      - { label: "Image", name: "image", widget: "image" }
                      - { label: "Alt", name: "alt", widget: "string" }
                  - { label: "Name", name: "name", widget: "string" }
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "About", name: "about", widget: "text" }
              - label: "Jannick"
                name: "jannick"
                widget: "object"
                collapsed: true
                fields:
                  - label: "Image"
                    name: "image"
                    widget: "object"
                    collapsed: true
                    fields:
                      - { label: "Image", name: "image", widget: "image" }
                      - { label: "Alt", name: "alt", widget: "string" }
                  - { label: "Name", name: "name", widget: "string" }
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "About", name: "about", widget: "text" }
      - label: "Career Section"
        name: "career_section"
        widget: "object"
        collapsed: true
        fields:
          - { label: "Headline", name: "headline", widget: "string" }
          - { label: "Content", name: "content", widget: "markdown" }
  - name: "news"
    label: "News"
    folder: "news"
    i18n: true
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - label: "Image"
        name: "image"
        widget: "object"
        collapsed: true
        i18n: true
        fields:
          - { label: "Image", name: "image", widget: "image", i18n: duplicate }
          - { label: "Alt", name: "alt", widget: "string", i18n: true }
      - { label: "Excerpt", name: "excerpt", widget: "string", i18n: true }
      - { label: "Publish Date", name: "date", widget: "date", i18n: duplicate }
      - { label: "Content", name: "content", widget: "markdown", i18n: true }
  - name: "jobs"
    label: "Jobs"
    folder: "jobs"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "PDF", name: "vacancy_pdf", widget: "file" }
